heroes = {
    ana: {
        health: 250,
        armour: 0,
        shields: 0,
        primaryDamage: 70,
        secondaryDamage: 0,
        critMultiplier: 2,
        healing: 70,
        primaryRateOfFire: 0.8, // in seconds
        rateOfHealing: 0.8, // in seconds
        tickValue: 0.59, // in seconds
        abilities: {
            abilityName: {
                dmg: 0,
                statusEffect: null,
                duration: 0, // in seconds
            },
        },
    },
    ashe: {},
    baptiste: {},
    bastion: {},
    brigette: {},
    cassidy: {},
    dva: {},
    doomfist: {},
    echo: {},
    genji: {},
    hanzo: {},
    illari: {},
    junkrat: {},
    kiriko: {},
    lifeweaver: {},
    lucio: {},
    mauga: {},
    mei: {},
    mercy: {},
    moira: {},
    orisa: {},
    pharah: {},
    ramattra: {},
    reaper: {},
    reinhardt: {},
    roadhog: {},
    sigma: {},
    soujourn: {},
    soldier76: {},
    sombra: {},
    symmetra: {},
    torbjorn: {},
    tracer: {},
    widowmaker: {},
    winston: {},
    wreckingBall: {},
    zarya: {},
    zenyatta: {}    
}
